### ISSUE TITLE
Barter Container Location Incorrect Persistence 

### ISSUE THREAD

**Issue by ArZorMC** [cafestifflered/BarterContainer#3]
We noticed that the barter container is saved to a specific coordinate in the world. This is expected behavior but becomes an issue when the barter container is broken. That block coordinate is still owned by the player that made the shop. 
If another player attempts to place a block in that location, they cannot. 
If the original shop owner places a barrel back in that location it is recognized as a barter container

**Comment by cafestifflered** [comment]
Solution may be to make container breaking cancel. Container owner has to empty it first, then close the shop, then they can break it.
